#redis:
#  address:
#    - "120.46.80.186:7001"
#    - "120.46.80.186:7002"
#    - "120.46.80.186:7003"
#    - "120.46.80.186:7004"
#    - "120.46.80.186:7005"
#    - "120.46.80.186:7006"
#  password: "mypassword"
#  routeByLatency: "true"
#  dialTimeout:    10s
#  readTimeout:    10s
#  writeTimeout:   10s

redis:
  address: 117.50.85.130:6379
  password: "mypassword"
  routeByLatency: "true"
  dialTimeout:    10s
  readTimeout:    10s
  writeTimeout:   10s

PG:
  dataSource: "host=117.50.85.130 user=myuser password=mypassword dbname=mydatabase port=5432 sslmode=disable TimeZone=Asia/Shanghai search_path=public"

Doris:
  dataSource: "root:mypassword@tcp(117.50.85.130:9030)/mydb?charset=utf8mb4&parseTime=True&loc=Local"
  FEIP: "117.50.85.130"
  FEPORT: "8040"
  FEDB: "mydb"

Kafka:
  Addr: 117.50.85.130:9092
  protocol: tcp
  groupID: mygroup

nacos:
  serverAddr: 117.50.85.130
  serverPort: 8848
  clientNameId: namespaceid
  username: myuser
  password: mypassword
  