redis:
  address:
    - "120.46.80.186:7001"
    - "120.46.80.186:7002"
    - "120.46.80.186:7003"
    - "120.46.80.186:7004"
    - "120.46.80.186:7005"
    - "120.46.80.186:7006"
  password: "mypassword"
  routeByLatency: "true"
  dialTimeout:    10s
  readTimeout:    10s
  writeTimeout:   10s

PG:
  dataSource: "host=120.46.80.186 user=myuser password=mypassword dbname=mydatabase port=5432 sslmode=disable TimeZone=Asia/Shanghai"

Doris:
  dataSource: "root:mypassword@tcp(120.46.80.186:9031)/mydb?charset=utf8mb4&parseTime=True&loc=Local"

Kafka:
  Addr: 120.46.80.186:9092
  protocol: tcp

nacos:
  serverAddr: 120.46.80.186
  serverPort: 8848
  clientNameId: namespaceid
  username: myuser
  password: mypassword
  